defmodule AshVault.Actions.DestroyKeys do
  @moduledoc """
  Generic action implementation that crypto-erases this scope: every key version for it is
  destroyed and the scope is tombstoned.

  This is irreversible. Every value encrypted under the scope becomes permanently
  unrecoverable, and later reads return `AshVault.Errors.KeyDestroyed`.

  Generated by `AshVault.Transformers.SetupEncryption` when `key_lifecycle.destroy` is set
  on a `scope_owner? true` resource. Ordinary actors and policies apply.

  Returns `{:ok, %AshVault.Erasure{}}` — the scope that was erased and the time the
  erasure completed.

  It used to return the action's `returns: :atom` `:ok`, which `Ash.run_action/1` wrapped
  into `{:ok, :ok}`. That reads like a typo and tells a caller nothing it did not already
  know; see `AshVault.Erasure`.
  """

  use Ash.Resource.Actions.Implementation

  @doc false
  @impl Ash.Resource.Actions.Implementation
  def run(input, _opts, context) do
    ctx = AshVault.Context.Builder.from_action_input(input, context)
    vault = AshVault.Info.vault!(input.resource, ctx.ash_context)
    scope = AshVault.Info.scope_module(input.resource).resolve!(ctx)

    :ok = AshVault.destroy_keys!(vault, scope, ctx)

    # After the provider confirms, never before: this timestamp is a time by which the
    # key material was definitely gone.
    {:ok, %AshVault.Erasure{scope: scope, destroyed_at: DateTime.utc_now()}}
  rescue
    error in [
      AshVault.Errors.MissingScope,
      AshVault.Errors.KeyNotFound,
      AshVault.Errors.KeyDestroyed,
      AshVault.Errors.ProviderUnavailable
    ] ->
      {:error, error}
  end
end
