defmodule AshVault.Actions.RotateKey do
  @moduledoc """
  Generic action implementation that rotates this scope's encryption key.

  Generated by `AshVault.Transformers.SetupEncryption` when `key_lifecycle.rotate` is set
  on a `scope_owner? true` resource. It is an ordinary generic action, so actors, policies
  and authorization work exactly as they do everywhere else — AshVault adds no
  authorization of its own.

  Returns `{:ok, new_key_version}`.
  """

  use Ash.Resource.Actions.Implementation

  @doc false
  @impl Ash.Resource.Actions.Implementation
  def run(input, _opts, context) do
    ctx = AshVault.Context.Builder.from_action_input(input, context)
    vault = AshVault.Info.vault!(input.resource, ctx.ash_context)
    scope = AshVault.Info.scope_module(input.resource).resolve!(ctx)

    AshVault.rotate_key!(vault, scope, ctx)
  rescue
    error in [
      AshVault.Errors.MissingScope,
      AshVault.Errors.KeyNotFound,
      AshVault.Errors.KeyDestroyed,
      AshVault.Errors.ProviderUnavailable
    ] ->
      {:error, error}
  end
end
