defmodule Example.Repo.Migrations.AddAuthUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:auth_users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:hashed_password, :text)
      add(:encrypted_email, :binary)
      add(:email_lookup, :binary)
    end

    create unique_index(:auth_users, [:org_id, :email_lookup],
             name: "auth_users_email_lookup_unique_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:auth_users, [:org_id, :email_lookup],
        name: "auth_users_email_lookup_unique_index"
      )
    )

    drop(table(:auth_users))
  end
end
