defmodule Example.Repo.Migrations.AddApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_keys, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:label, :text)
      add(:revoked_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(table(:api_keys))
  end
end
