defmodule Example.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contacts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:label, :text)
      add(:encrypted_phone, :binary)
    end

    create table(:organizations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
    end

    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:name, :text)
      add(:encrypted_email, :binary)
    end
  end

  def down do
    drop(table(:users))

    drop(table(:organizations))

    drop(table(:contacts))
  end
end
